import { Sub } from "./subjects";
export const subjects:Sub[]=[
    {
       subjectCode:'CS12',
       subjectAttendance:Math.floor(Math.random()*100),
       subjectMarks:Math.floor(Math.random()*100)
    },
    {
        subjectCode:'CS34',
        subjectAttendance:Math.floor(Math.random()*100),
        subjectMarks:Math.floor(Math.random()*100)
    },
    {
        subjectCode:'CS56',
        subjectAttendance:Math.floor(Math.random()*100),
        subjectMarks:Math.floor(Math.random()*100)
     },
     {
        subjectCode:'CS78',
        subjectAttendance:Math.floor(Math.random()*100),
        subjectMarks:Math.floor(Math.random()*100)
     },
     {
        subjectCode:'CS910',
        subjectAttendance:Math.floor(Math.random()*100),
        subjectMarks:Math.floor(Math.random()*100)
     },
     {
        subjectCode:'CS1112',
        subjectAttendance:Math.floor(Math.random()*100),
        subjectMarks:Math.floor(Math.random()*100)
     }
]